// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhent8t9gJWJeJSh76iVGfWvIHQdZerMM',
    appId: '1:815575323713:web:cfdff629db27af358d22c0',
    messagingSenderId: '815575323713',
    projectId: 'jenisovecoolpoznamky-bfb63',
    authDomain: 'jenisovecoolpoznamky-bfb63.firebaseapp.com',
    storageBucket: 'jenisovecoolpoznamky-bfb63.appspot.com',
    measurementId: 'G-ZQ6SWPK7V1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcF8pdYtaTNGfEja4f6odbP0UMnKeJRE',
    appId: '1:815575323713:android:88aa3a5bedef1cbf8d22c0',
    messagingSenderId: '815575323713',
    projectId: 'jenisovecoolpoznamky-bfb63',
    storageBucket: 'jenisovecoolpoznamky-bfb63.appspot.com',
  );
}
